### ISSUE TITLE
Problems running tests in PhantomJS

### ISSUE THREAD

**Issue by necolas** [flightjs/jasmine-flight#9]
Every time I try to get Karma to run Flight unit tests in Phantom, it can't. No problems with real browsers. The terminal output is full of this:

```
TypeError: 'undefined' is not a function (evaluating 'function(registry, Component) {
            registry.reset();
            this.Component = Component;
          }.bind(this)')
```

Resulting in `this.Component` being `null`.

**Comment by derrickpelletier** [comment]
I think this issue is before the repo was using Karma, so just wanted to post an update to how I resolved this issue with karma runner.

You'll need to shim prior to the `requirejs` framework being loaded. Loading in frameworks essentially just prepends the `files` array. So just remove from `requirejs` from the frameworks list, and add your es5-shim/sham before loading in the requirejs framework. Like so in your `karma.conf.js`:

```javascript
    browsers: ['PhantomJS'],
    frameworks: ['jasmine'],
    files: [

      {pattern: 'bower_components/es5-shim/es5-shim.js', watch: false},
      {pattern: 'bower_components/es5-shim/es5-sham.js', watch: false},

      {pattern: 'node_modules/requirejs/require.js', watch: false},
      {pattern: 'node_modules/karma-requirejs/lib/adapter.js', watch: false},

      //...etc
    ]
```
